flask_app/store/routes.py
from ..forms import AddToCartForm, RemoveFromCartForm, PlaceOrderForm
from ..models import User, Item
from ..utils import current_time


# New Python Package
import requests



# 3rd-party packages
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    Blueprint,
    session,
    g,
)
from flask_mongoengine import MongoEngine
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)
from flask_bcrypt import Bcrypt
from flask_app import db
from werkzeug.utils import secure_filename

# stdlib
from datetime import datetime
import io
import base64

store = Blueprint("store", __name__)




@store.route("/", methods=["GET", "POST"])
def index():

    return render_template("index.html")



@store.route("/about")
def about():
    return render_template("about.html")

@store.route("/setup")
def setup():
    
    Item.drop_collection()
    
    res = requests.get("https://fakestoreapi.com/products")
    res_json = res.json()
    for i in res_json:
        item = Item (
            item_id = str(i["id"]),
            title = i["title"],
            price = str(i["price"]),
            description = i["description"],
            image = i["image"],
            status = 0,
            count = "1"

        )
        item.save()
    
    
    return redirect(url_for("store.shop"))
    
    


@store.route("/shop")
def shop():

    items_available = Item.objects(status=0)


    return render_template("shop.html", items_for_sale=items_available)




@store.route("/items/<id>", methods=["GET", "POST"])
def item_detail(id):

    i = Item.objects.get(item_id=id)
    
    form = AddToCartForm()
    if form.validate_on_submit():
        i_id = Item.objects(item_id=id).get()
        i_id.update(added_to_cart_by=current_user._get_current_object())
        i_id.save()
        


    return render_template("item_detail.html", item=i, form=form)


@store.route("/user/cart", methods=["GET", "POST"])
def user_cart():
    form = RemoveFromCartForm()
    form2 = PlaceOrderForm()

    items_added_to_cart = Item.objects(added_to_cart_by=current_user._get_current_object())

    return render_template("cart.html", items_in_cart=items_added_to_cart, form=form, form2=form2)




@store.route("/user/cart/remove-all", methods=["GET", "POST"])
def user_cart_remove():

    
    items_added_to_cart = Item.objects(added_to_cart_by=current_user._get_current_object())

    form = RemoveFromCartForm()
    
    if form.validate_on_submit():
        i_atc = Item.objects(added_to_cart_by=current_user._get_current_object())
        for i in i_atc:
            i.update(added_to_cart_by=None)
            i.save()

    form2 = PlaceOrderForm()

    return render_template("cart.html", items_in_cart=items_added_to_cart, form=form, form2=form2)




@store.route("/user/cart/place-order", methods=["GET", "POST"])
def user_cart_place_order():

    items_added_to_cart = Item.objects(added_to_cart_by=current_user._get_current_object())

    form = RemoveFromCartForm()

    form2 = PlaceOrderForm()
    if form2.validate_on_submit():
        for i in items_added_to_cart:
            i.update(status=1)
            i.update(ordered_by=current_user._get_current_object())
            i.update(count="0")
            i.update(added_to_cart_by=None)


        

        # Redirect to order page
        return redirect(url_for("store.user_order_confirmation"))
    

    return render_template("cart.html", items_in_cart=items_added_to_cart, form=form, form2=form2)




@store.route("/user/order-confirmation", methods=["GET", "POST"])
def user_order_confirmation():
    
    return render_template("order_confirmation.html")


@store.route("/user/orders", methods=["GET", "POST"])
def user_orders():
    i_ordered = Item.objects(ordered_by=current_user._get_current_object())

    return render_template("orders.html", i_ordered=i_ordered)

flask_app/users/routes.py
from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateEmailForm
from ..models import User


# 3rd-party packages
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    Blueprint,
    session,
    g,
)
from flask_mongoengine import MongoEngine
from flask_login import (
    LoginManager,
    current_user,
    login_user,
    logout_user,
    login_required,
)
from flask_bcrypt import Bcrypt
from werkzeug.utils import secure_filename

# stdlib
from datetime import datetime
import io
import base64

users = Blueprint("users", __name__)




@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("store.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("store.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("store.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    email_form = UpdateEmailForm()

    if email_form.validate_on_submit():
        current_user.modify(email=email_form.email.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        email_form=email_form,
    )

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            About
        </h1>
        <h6>
            This is a personal e-commerce website where I sell whatever it is that I want to sell. Items could be clothes, electronics, shoes, etc. People that want to order something from the website have to first make an account by signing up. Once signed in, a customer can access the shop. The customer can then view the details of various items, add items to their cart, and place orders. To view past orders, a customer can click on the orders tab.
        </h6>
    </div>
</div>
<div class="row">
    <div class="col" style="text-align: center;">
        <h1> </h1>
    </div>
</div>
<div class="row">
    <div class="col" style="text-align: center;">
        <h1> </h1>
    </div>
</div>
<div class="row">
    <div class="col" style="text-align: center;">
        <h1> </h1>
    </div>
</div>
<div class="row">
    <div class="col" style="text-align: center;">
        <h6>
            Website created by Ishan Dutta
        </h6>
        <b>
            <a href="{{ url_for('store.index') }}">
                Go back to the home page
            </a>
        </b>
    </div>
</div>

{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h1>Hello, {{ current_user.username }}!</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <h6>Current Username: {{ current_user.username }}</h6>
    </div>
</div>
<div class="row">
    <div class="col">
        <h6>Current Email: {{ current_user.email }}</h6>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ email_form.csrf_token }}
            <div class="form-group">
                {{ email_form.email.label(class="form-control-label") }}
                {{ email_form.email(class="form-control form-control-lg") }}

                {% if email_form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in email_form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ email_form.submit }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('store.index') }}">
    <h4>Return to Home</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>ID's Personal Store</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/cart.html
{% extends "header.html" %}
{% block content %}

{% if current_user.is_authenticated %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Cart
        </h1>
    </div>
</div>

<table class="table table-striped">
    <thead>
     <tr>
      <th>Item</th>
      <th>Name</th>
      <th>Price</th>
     </tr>
    </thead>
    <tbody>         
    {% for item in items_in_cart %}
        <tr>
        <td class="w-25">
            <img src={{item.image}} class="img-fluid img-thumbnail">
        </td>
        <td>
            <a href="{{ url_for('store.item_detail', id=item.item_id) }}">
                {{item.title}}
            </a>
        </td>
        <td>{{item.price}}</td>
        </tr>
    {% endfor %}   
    </tbody>
</table>

<div class="row">
    <div class="col" style="text-align: center;">
        <form action="{{ url_for('store.user_cart_place_order') }}" method="post">
            {{ form2.csrf_token }}
            <div class="form-group">
                {{ form2.submit(class="form-control form-control-lg") }}
            </div>
        </form>
        <form action="{{ url_for('store.user_cart_remove') }}" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% else %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Please sign up and/or log in to access cart!
        </h1>
        <b>
            <a href="{{ url_for('store.index') }}">
                Go back to the home page
            </a>
        </b>
    </div>
</div>


{% endif %}
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('store.index') }}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('store.shop') }}">
                    Shop
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('store.user_orders') }}">
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('store.user_cart') }}">
                    Cart
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('store.about') }}">
                    About
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Sign Up
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('store.about') }}">
                    About
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col" style="text-align: center;">
        <h2>Welcome to my store! </h2>
    </div>
</div>
<div class="row">
    <div class="col" style="text-align: center;">
        <h2>
            <img src="https://pngimage.net/wp-content/uploads/2018/05/blue-shopping-cart-png-1.png" alt="blue shopping cart png 1" class="w-50">
        </h2>
    </div>
</div>
{% endblock %}

flask_app/templates/item_detail.html
{% extends "header.html" %}
{% block content %}


{% if item %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            {{item.title}}
        </h1>
        <h2>
            <img src={{item.image}} class="w-50">
        </h2>
        <h2>
            Price: {{item.price}}
        </h2>
        <h2>
            In Stock: {{item.count}}
        </h2>
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
        <b>
            <a href="{{ url_for('store.shop') }}">
                Go back to Shop
            </a>
        </b>
    </div>
</div>



{% endif %}
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Sign Up!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/order_confirmation.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Order Confirmation
        </h1>
        <h6>
            Successfully Placed Order!
        </h6>
        <h6>
            Future order updates will be sent to {{ current_user.email }}
        </h6>
        <b>
            <a href="{{ url_for('store.index') }}">
                Go back to the home page
            </a>
        </b>
    </div>
</div>


{% endblock %}

flask_app/templates/orders.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Orders
        </h1>
        <h6>
            All Items From Past Orders
        </h6>
    </div>
</div>

<table class="table table-striped">
    <thead>
     <tr>
      <th>Item</th>
      <th>Name</th>
      <th>Price</th>
     </tr>
    </thead>
    <tbody>         
    {% for item in i_ordered %}
        <tr>
        <td class="w-25">
            <img src={{item.image}} class="img-fluid img-thumbnail">
        </td>
        <td>
            <a href="{{ url_for('store.item_detail', id=item.item_id) }}">
                {{item.title}}
            </a>
        </td>
        <td>{{item.price}}</td>
        </tr>
    {% endfor %}   
    </tbody>
</table>

{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Sign Up</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>

<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

flask_app/templates/shop.html
{% extends "header.html" %}
{% block content %}

{% if current_user.is_authenticated %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h1>
            Shop
        </h1>
    </div>
</div>
<table class="table table-striped">
    <thead>
     <tr>
      <th>Item</th>
      <th>Name</th>
      <th>Price</th>
     </tr>
    </thead>
    <tbody>         
    {% for item in items_for_sale %}
        <tr>
        <td class="w-25">
            <img src={{item.image}} class="img-fluid img-thumbnail">
        </td>
                <td>
                    <a href="{{ url_for('store.item_detail', id=item.item_id) }}">
                        {{item.title}}
                    </a>
                </td>
                    <td>{{item.price}}</td>       
        </tr>
    {% endfor %}   
    </tbody>
</table>

{% else %}
<div class="row">
    <div class="col" style="text-align: center;">
        <h2>
            To access exclusive shop, please sign up and/or log in!
        </h2>
        <b>
            <a href="{{ url_for('store.index') }}">
                Go back to the home page
            </a>
        </b>
    </div>
</div>

{% endif %}
{% endblock %}